#!/bin/bash
# My first script
#rm -rf parts
#mkdir parts
#cat items/poliScrapy/history/a2d7f08f9c7511e6a616a45e60edbd8f.jl | jq -c -M '.data[]' | split -l 1 - parts

for f in `cat input.json | jq -r '. | keys[]'` ; do
  cat input.json | jq ". | .$f" > $f.json
done

